import { Component, OnInit } from '@angular/core';
import { ReportService } from '../../../services/report/report.service';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { ConfirmationService, MessageService } from 'primeng/api';
import { AuthUser } from '../../../models/auth/auth.model';
import { AuthService } from '../../../services/auth/auth.service';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-registered-users-report',
  templateUrl: './registered-users-report.component.html',
  styleUrls: ['./registered-users-report.component.scss']
})
export class RegisteredUsersReportComponent implements OnInit {
  user$: Observable<AuthUser | null>;
  loggedInUser: AuthUser | null = null;

  users: any[] = [];
  filteredUsers: any[] = [];
  searchCriteria: string = '';
  page: number = 1;
  order: string = 'firstName';
  reverse: boolean = false;
  minDate: string = '';
  maxDate: string = '';
  dateType: string = 'registeredDate';
  days: string = '';

  constructor(
    private reportService: ReportService,
    private confirmationService: ConfirmationService,
    private messageService: MessageService,
    private authService: AuthService
  ) { 
    this.user$ = this.authService.userDetails$;
  }

  ngOnInit(): void {
    this.loadReport();
    this.authService.userDetails$.subscribe(user => {
      this.loggedInUser = user;
    });
  }

  loadReport(): void {
    this.reportService.getRegisteredUsersReport().subscribe(data => {
      this.users = data;
      this.filteredUsers = data;
    });
  }

  filterByDateRange(): void {
    const minDate = this.minDate ? new Date(this.minDate) : null;
    const maxDate = this.maxDate ? new Date(this.maxDate) : null;

    this.filteredUsers = this.users.filter(user => {
        const userDate = new Date(user[this.dateType]);
        userDate.setHours(0, 0, 0, 0); 

        if (minDate) {
            minDate.setHours(0, 0, 0, 0);
        }
        if (maxDate) {
            maxDate.setHours(23, 59, 59, 999);
        }

        if (minDate && maxDate) {
            return userDate >= minDate && userDate <= maxDate;
        } else if (minDate) {
            return userDate >= minDate;
        } else if (maxDate) {
            return userDate <= maxDate;
        } else {
            return true;
        }
    });

    this.sortUsers();
  }

  filterByDays(): void {
    const days = parseInt(this.days);
    const today = new Date();
    const pastDate = new Date();
    pastDate.setDate(today.getDate() - days);

    this.filteredUsers = this.users.filter(user => {
      const userDate = new Date(user[this.dateType]);
      return userDate >= pastDate && userDate <= today;
    });

    this.sortUsers();
  }

  clearFilters(): void {
    this.minDate = '';
    this.maxDate = '';
    this.days = '';
    this.filteredUsers = [...this.users];
  }

  setOrder(value: string, reverse: boolean): void {
    this.order = value;
    this.reverse = reverse;
    this.sortUsers();
  }

  sortUsers(): void {
    this.filteredUsers.sort((a, b) => {
      let comparison = 0;
      if (a[this.order] > b[this.order]) {
        comparison = 1;
      } else if (a[this.order] < b[this.order]) {
        comparison = -1;
      }
      return this.reverse ? comparison * -1 : comparison;
    });
  }

  exportToPDF(): void {
    this.confirmationService.confirm({
      header: 'Confirmation',
      message: 'Are you sure you want to export this report?',
      accept: () => {
        const doc = new jsPDF();
        const currentTime = new Date();
        const date = currentTime.toLocaleDateString().replace(/\//g, '-');
        const time = currentTime.toLocaleTimeString().replace(/:/g, '-');

        let dateRangeText = '';
        if (this.minDate && this.maxDate) {
          dateRangeText = `Applied Filter: Users registered between ${this.minDate} and ${this.maxDate}`;
        } else if (this.days) {
          dateRangeText = `Applied Filter: Users registered in the last ${this.days} days.`;
        }

        const img = new Image();
        img.src = 'assets/company-logo.png';
        img.onload = () => {
          doc.addImage(img, 'PNG', 10, 15, 50, 20);

          doc.setFont('Arial');

          doc.setFontSize(18);
          doc.text('EPI-USE Africa', 70, 20);

          doc.setFontSize(10);
          doc.text(`Generated on:`, 70, 25);

          doc.setFontSize(10);
          doc.text(`Date: ${date} Time: ${time}`, 70, 30);

          const generatedBy = this.loggedInUser ? `${this.loggedInUser.firstName} ${this.loggedInUser.surname}` : 'Unknown User';
          doc.setFontSize(10);
          doc.setFont('Arial', 'normal');
          doc.text(`Report generated by: ${generatedBy}`, 70, 35);

          doc.setLineWidth(0.5);
          doc.line(10, 40, 200, 40);

          doc.setFontSize(14);
          doc.setFont('Arial', 'bold');
          doc.text('Registered Users Report', 10, 45);

          if (dateRangeText) {
            doc.setFontSize(11);
            doc.setFont('Arial', 'normal');
            doc.text(dateRangeText, 10, 50);
          } else {
            doc.setFontSize(11);
            doc.setFont('Arial', 'normal');
            doc.text('No filter applied', 10, 50);
          }

          doc.setFontSize(12);
          doc.setFont('Arial', 'bold');
          doc.text('List of Registered Users', 10, 60);

          (doc as any).autoTable({
            startY: 65,
            head: [['First Name', 'Last Name', 'Email', 'Registered Date']],
            body: this.filteredUsers.map(user => [user.firstName, user.lastName, user.email, user.registeredDate]),
            headStyles: { fillColor: [0, 24, 68] },
            didDrawPage: (data: any) => {
              const pageSize = (doc as any).internal.pageSize;
              const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
              doc.setFontSize(10);
              doc.setFont('Arial', 'normal');
              doc.text('Generated from the Test Script Tracker Application', data.settings.margin.left, pageHeight - 10);
              doc.text(`Page ${data.pageNumber}`, pageSize.width - data.settings.margin.right - 10, pageHeight - 10);
            }
          });

          doc.save(`RegisteredUsersReport_${date}_${time}.pdf`);
          this.messageService.add({ severity: 'success', summary: 'Success', detail: 'Report exported successfully', key: 'bc' });
        };
      },
      reject: () => {
        this.messageService.add({ severity: 'info', summary: 'Cancelled', detail: 'Export cancelled', key: 'bc' });
      }
    });
  }
}